# -*- coding: utf-8 -*-
"""carga_datos

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sy1K6w1l2LX5aAmD78qjRzMkwXbdZ1xp
"""

# Funciones para carga de datos

def cargar_datos(ruta):
    pass