# -*- coding: utf-8 -*-
"""metricas

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GYRrrQ_d9pKZ_9jJWOtH05CK9-vK6zcb
"""

# Funciones para cálculo de métricas

def calcular_metricas(df):
    pass