# -*- coding: utf-8 -*-
"""procesamiento_datos

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1EdVW9nl-OGM7wUabthsMvbQD--UGkLGL
"""

# Funciones para procesamiento de datos

def procesar_datos(df):
    pass